# Autostart
exec-once = waybar
exec-once = mako

# Keybindings
$mainMod = SUPER

bind = $mainMod, SPACE, exec, wofi --show drun
bind = $mainMod, Q, killactive
bind = $mainMod, F, fullscreen
bind = $mainMod, L, exec, hyprlock
bind = $mainMod SHIFT, Q, exit
